### ISSUE TITLE
Fails to build. Possibly related to case sensitive file systems?

### ISSUE THREAD

**Issue by gameboycjp** [erayzesen/QuarkPhysics#1]
../QuarkPhysics/qjoint.h:30:10: fatal error: QRigidBody.h: No such file or directory
   30 | #include "QRigidBody.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.

I get a bunch of no file or directory messages trying to build the project. Perhaps my FS is case sensitive? On Garuda Linux, with a BTRFS filesystem.

**Comment by erayzesen** [comment]
Sorry, I answered a little late. I've solved this problem for the next version and I will commit soon. 

Thank you.
