### ISSUE TITLE
Pressurized soft bodies can roll on their own

### ISSUE THREAD

**Issue by gameboycjp** [erayzesen/QuarkPhysics#3]
Gridded pressurized soft body meshes of high poly spheres roll to the right on completely flat ground. To recreate, change the spawned soft body in examplesceneblobs.cpp to have a poly count of 32 or higher, and up the rigidities.

**Comment by erayzesen** [comment]
Thank you. If you are using the area preserving feature in soft body objects, you need to release the internal springs. You can use the SetPassivationOfInternalSpringsEnabled(bool value) method for this. If you don't do this, both the internal springs and other pressure constraints will cause stress. Similarly, it is not recommended to use the shape matching feature.

**Edit**: I also plan to create a detailed wiki page for these in the future. Rigid bodies have a more concrete concept, but soft bodies inherently require a bit more information.

**Comment by gameboycjp** [comment]
Yeah, no problem, I've been looking for a softbody physics engine for some time, and appreciate that you're sharing your work. 
I am not using the shape matching, and I have the internal springs disabled, as far as I can tell. The perams for my recreation case is as follows:
```
griddedPressuredBody->AddMesh( QMesh::CreateWithPolygon(32,64,QVector::Zero(),-1 ) );
griddedPressuredBody->SetRigidity(0.8f)->SetPosition(mousePosition)->SetMass(0.5f);
griddedPressuredBody->SetAreaPreservingEnabled(true)->SetPassivationOfInternalSpringsEnabled(true)->SetAreaPreservingRigidity(0.5f);
```
It's a change to lines 61 to 63 in examplesceneblobs.cpp I made to test this when I noticed similar behaviour in godot.

**Comment by erayzesen** [comment]
I will make a test again with your codes at tomorrow. I'll go back to you again.

**Comment by erayzesen** [comment]
I have tested it with the example you mentioned. Although the area-preserving implementation works well, the attempt to balance the particles' center of mass results in a movement behavior towards the right side of the object as a whole. It is an undesirable behavior and needs to be resolved, so let this issue remain open. Thanks for the test and feedback.

**Comment by gameboycjp** [comment]
I tried building with the latest commits, but things seem more broken now. In ExampleSceneMixedBodies and ExampleSceneSoftBodies, soft bodies seem to spin themselves to certain orientations. ExampleSceneBlobs does not spawn any blobs.

**Comment by erayzesen** [comment]
> I tried building with the latest commits, but things seem more broken now. In ExampleSceneMixedBodies and ExampleSceneSoftBodies, soft bodies seem to spin themselves to certain orientations. ExampleSceneBlobs does not spawn any blobs.

The recent commits were about shape matching problems. Since we are still in the development versions and do not have a stable release yet, you may encounter various issues when trying out the commits. I will soon be working on the issues mentioned here and will write about them as well.

**Comment by erayzesen** [comment]
I addressed this issue in the latest update. Firstly, there is no calculation error in the area preserving implementation that could cause this problem. However, as the number of particles increases, the pressure exerted by the particles' weights on the area that needs to be preserved by the body causes it to move in one direction. To prevent this, the weight of the body can be reduced, the newly added air friction feature in the library for bodies can be increased (default is 0.01), the ratio of the preserved area can be decreased, and the existing potential pressure can be reduced. In the latest update, the particle count has been increased to 32 in the blobs example scene to observe the positive effect of air friction.  If you don't have any further questions or issues, I will close this issue for now.
